name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - Streamario_web_backend/**
  workflow_dispatch:

env:
  GCP_PROJECT_ID: streamerio-472706
  GCP_REGION: asia-northeast1
  ARTIFACT_REGISTRY_REPO: streamario
  IMAGE_NAME: asia-northeast1-docker.pkg.dev/streamario/streamario/streamario-web-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: 'read'
        id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/282618030957/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-pool'
          service_account: github-actions@streamerio-472706.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Set Image Tag Name
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          echo "IMAGE_TAG=${TAG}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -t ${IMAGE_NAME}:latest \
            -f Streamario_web_backend/Dockerfile \
            ./Streamario_web_backend
          docker push ${IMAGE_NAME}:${IMAGE_TAG}
          docker push ${IMAGE_NAME}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy streamario-web-backend \
            --image ${IMAGE_NAME}:${IMAGE_TAG} \
            --platform managed \
            --region ${GCP_REGION} \
            --allow-unauthenticated
